### ISSUE TITLE
怎么检测另一个进程呢?

### ISSUE THREAD

**Issue by Ron2014** [lsg2020/swt#1]
`[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua main
[:00000009] LAUNCH snlua debug_console 8000
[:00000009] Start debug console at 127.0.0.1:8000
[:0000000a] LAUNCH snlua swt/master
[:0000000b] LAUNCH snlua swt/agent
[:00000002] KILL self
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil
connect ws:///debug failed: ./skynet/lualib/http/websocket.lua:427: invalid protocol: nil`

请教一下哦，我有自己的一个skynet进程跑在10001端口（我们的游戏逻辑服），是不是需要改一下配置来监测这个进程？
目前打开管理页面会报出如上错误，看上去像是websocket链接的IP和端口号还是空的

**Comment by lsg2020** [comment]
启动后在这个页面提交监控的节点地址  端口信息是你的节点启动agent的时候配置的信息 
例如: swt.start_agent("app", "node1", "0.0.0.0:9528")
配置: 127.0.0.1:9528
http://127.0.0.1:9527/admin#/dashboard

**Comment by Ron2014** [comment]
对比了一下云风的skynet和这个项目的skynet，发现网络层有动过，好像就改了一下websocket吧？哇，难怪我swt/agent老是没起成功

**Comment by lsg2020** [comment]
websocket有一点修改，可以参考这个提交
https://github.com/lsg2020/skynet/commit/633ace5c3ecda4853be3cbd68a582e93ab7dc48a

**Comment by Ron2014** [comment]
大神，可以加下QQ号么，我觉得这个项目真心牛逼，想好好研究一下。3381166832
