### ISSUE TITLE
火焰图显示不出lua c 层 堆栈？

### ISSUE THREAD

**Issue by cloudfreexiao** [lsg2020/swt#19]
目前我使用的情况 每次抓的数据 通过 web 页面查看 好像 都没有 包括c层的 调用堆栈 但是看代码 好像是有 收集 c 层 部分
有点疑惑是 我抓取的数据不够 还是 什么原因？

**Comment by lsg2020** [comment]
嗯，最近有点忙，等我有空时研究看看哈

**Comment by cloudfreexiao** [comment]
好的 多谢了～～
