### ISSUE TITLE
增加 对 特定服务 过滤 profiler 选项

### ISSUE THREAD

**Issue by cloudfreexiao** [lsg2020/swt#4]
在 压测 阶段 agent 由于 比较多 导致 web 页面 不好 查看 所以希望 增加 过滤选项
目前 已经有的
```lua
        local skynet = require "skynet"
        local service_list = skynet.call(".launcher", "lua", "list")
        print(service_list)
```

**Comment by lsg2020** [comment]
![image](https://user-images.githubusercontent.com/63353050/102590070-f80e3c80-414a-11eb-9afb-f7e1ac8f636c.png)
可以通过服务名和地址过滤需要检测的服务吧

**Comment by cloudfreexiao** [comment]
啊 没看到 我试试 不好意思
