### ISSUE TITLE
如何把 dump 信息 做 排序显示

### ISSUE THREAD

**Issue by cloudfreexiao** [lsg2020/swt#5]
原版 profile 有个 排序显示的 功能 https://github.com/lvzixun/luaprofile/blob/master/profile.c#L552
递归 对 每个 table 里对 children 中 cpu 以 rettime 内存 以 alloc_count 做排序 ?

**Comment by lsg2020** [comment]
页面上现在没做 dump信息的展示，后面有空时可以加下

**Comment by cloudfreexiao** [comment]
还有问题 想 问下 我看数据只是 采集到 lua 层 吗

**Comment by lsg2020** [comment]
恩,lua层调用c层的耗时算在 lua的函数消耗上的

**Comment by cloudfreexiao** [comment]
请教下: github 上有个 flamegraph 显示的库 不知道 本仓库和它有啥区别 ？

 https://github.com/spiermar/d3-flame-graph

**Comment by lsg2020** [comment]
https://github.com/hyj1991/easy-monitor/blob/easy-monitor%402.1.9/src_view/src/views/common/profiler/flamegraph.vue 你可以参考下这个，只是修改数据格式使用自己的数据格式

**Comment by cloudfreexiao** [comment]
好的
