### ISSUE TITLE
suspend_sleep 出现signal 0问题

### ISSUE THREAD

**Issue by wilsonloo** [lsg2020/swt#9]
你好，我有个问题折腾了几天。跑当前swt时没有问题，能够正确的统计出各种数据；但是当我开始将swt嵌入到自己项目时，会出现 signal 0 的问题，例如我将 handle_debug.lua 部分代码改为：
``` lua
local code_template = [[
    local skynet = require 'znet'
    local json   = require "cjson"
    local profile = require "profile"
    local debug_address = %d
    local session = %s
    local function debug_print(...)
        local args = {...}
        local out = {}
        for k, v in ipairs(args) do
            if type(v) == "table" then
                out[k] = json.encode(v)
            else
                out[k] = tostring(v)
            end
        end
        skynet.send(debug_address, 'lua', 'print', session, table.concat(out, '\t'))
    end
    local env = setmetatable({print = debug_print}, {__index = _G})
    profile.start()
    skynet.sleep(2 * 100, nil, "mark")
    debug_print(profile.stop())
    print('ok')
]]
```
在 http://127.0.0.1:9527/admin#/profiler 尝试进行持续2秒内的性能统计时，会出现：
``` c
>>      ret     false
>>      output  ./skynet/lualib/skynet.lua:396: signal 0
stack traceback:
        ./skynet/lualib/skynet.lua:389: in upvalue 'suspend_sleep'
        ./skynet/lualib/skynet.lua:396: in function 'skynet.sleep'
        debug_run:20: in local 'start'
        ./skynet/lualib/skynet.lua:962: in function <./skynet/lualib/skynet.lua:959>
        [C]: in function 'xpcall'
        ./skynet/lualib/skynet.lua:966: in function 'skynet.pcall'
        ./skynet/lualib/skynet/inject.lua:59: in function 'skynet.inject'
        ./lualib/swt/swt/debug.lua:10: in local 'f'
        ./skynet/lualib/skynet/debug.lua:130: in upvalue 'f'
        ./skynet/lualib/skynet.lua:279: in function <./skynet/lualib/skynet.lua:251>
>>      session 526
stack traceback:
        ./service/swt/agent/handle_debug.lua:14: in upvalue 'agent_send'
        ./service/swt/agent/handle_debug.lua:108: in function <./service/swt/agent/handle_debug.lua:67>
        [C]: in function 'xpcall'
        ./service/swt/agent/handle_debug.lua:119: in upvalue 'func'
        ./skynet/lualib/skynet.lua:761: in upvalue 'f'
        ./skynet/lualib/skynet.lua:279: in function <./skynet/lualib/skynet.lua:251>
```
同时，如果注释 profile.start()/stop() 则不会出现该问题；profile也是使用 https://github.com/lsg2020/luaprofile
想问下对该问题有没有什么建议或思路， 感谢

**Comment by lsg2020** [comment]
你用的skynet和lua版本对不对，最新的版本已经升级到 lua5.4和skynet1.4

**Comment by lsg2020** [comment]
skynet 1.3版本可以使用 https://github.com/lsg2020/swt/commits/skynet_1.3

**Comment by wilsonloo** [comment]
> 
> 
> skynet 1.3版本可以使用 https://github.com/lsg2020/swt/commits/skynet_1.3

好， 我试试

**Comment by wilsonloo** [comment]
噗~~ 果真是lua版本问题，当下为5.3 升级到5.4 后正常了 👍

**Comment by wilsonloo** [comment]
> 
> 
> 噗~~ 果真是lua版本问题，当下为5.3 升级到5.4 后正常了 👍

今天重新复盘了，发现并非lua版本问题， 而是【我们项目skynet版本】与【swt skynet版本】有较大差异引起。

https://github.com/lsg2020/swt/commits/skynet_1.3 是在
【2020-12-14： fix cloudwu#1275 (cloudwu#1276) @698d032a9b22c4f1b8649f734c6421fb5e777f3e】
 基础上进行的修改，并且此后没有再合并最新的skynet；

我们项目的skynet 则已经更新到了
【2020-12-18：bugfix: make proto shared @4d88f96ed653c0d68dc22be2a03a87567448ae2d】

[2020-12-14，2020-12-18] 之间skynet 包含下修改：
![图片](https://user-images.githubusercontent.com/11910639/105164475-25864580-5b50-11eb-8e9c-0caf7f9cec19.png)

所以当我们项目尝试嵌入https://github.com/lsg2020/swt/tree/master/service/swt/agent后，
 进行http://127.0.0.1:9527/admin#/profiler 就会出现signal 0

**Comment by wilsonloo** [comment]
哈哈哈哈，发现问题了， 因为swt.skynet 为了配合profile 修改了service_snlua.c ，但这部分并没有 pull request 到 cloudwu/skynet， 所以不管我们项目skyent 如何从 cloadwu/skynet 同步都会失败的。

**Comment by lsg2020** [comment]
好的，skynet1.4 不支持lua_setallocf 自定义内存分配器了 (https://github.com/cloudwu/skynet/issues/1280)，  这块还没想好怎么改，所以没提pr, 使用的skynet版本有如下修改https://github.com/lsg2020/skynet/commit/aecaa9a7745bdbfa362d773ed8088622a707de63

**Comment by wilsonloo** [comment]
好的
